### ISSUE TITLE
Crash while clicking on Energy Bridge (Copy of Forum Crash Report)

### ISSUE THREAD

**Issue by Neakas** [portablejim/PowerConverters#31]
Hi there!

i am getting a Crash with your Mod when clicking on the Energy Bridge, while any Consumer or Producer is attached to it. No crash while theres nothing attached tho.The Conversion works fine, aslong as i dont click on the Bridge.Tested with Rf Consumer and Eu Producer. Worked.

Heres the Crash:

---- Minecraft Crash Report ----
// Don't do that.

Time: 29.04.15 15:19
Description: Unexpected error

"java.lang.ArrayIndexOutOfBoundsException: -1
at java.util.ArrayList.elementData(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at powercrystals.powerconverters.power.PowerSystemManager.getPowerSystemById(PowerSystemManager.java:82)
at powercrystals.powerconverters.gui.ContainerEnergyBridge.func_75137_b(ContainerEnergyBridge.java:94)
at net.minecraft.client.network.NetHandlerPlayClient.func_147245_a(NetHandlerPlayClient.java:1151)
at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:26)
at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:9)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1591)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)"

"

"-- Head --
Stacktrace:
at java.util.ArrayList.elementData(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at powercrystals.powerconverters.power.PowerSystemManager.getPowerSystemById(PowerSystemManager.java:82)
at powercrystals.powerconverters.gui.ContainerEnergyBridge.func_75137_b(ContainerEnergyBridge.java:94)
at net.minecraft.client.network.NetHandlerPlayClient.func_147245_a(NetHandlerPlayClient.java:1151)
at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:26)
at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:9)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)"

Its on a Server (obviously :D). Im Using forge-1.7.10-10.13.3.1389-1710ls-universal. "New" Gregtech is installed.

Tried it with an Older Version of your Mod "PowerConverters-1.7.10_3.1.1.60" and with the just released one "PowerConverters-1.7.10_3.2.0-jenkins.61"

**Comment by portablejim** [comment]
Fixed.

**Comment by Neakas** [comment]
Works wonderfully! I Thank You!
