### ISSUE TITLE
Some recipes broken with BC 7

### ISSUE THREAD

**Issue by zTorden** [portablejim/PowerConverters#46]
While launching game with PowerConverters-1.7.10_3.3.0-jenkins.75.jar (also tried PowerConverters-1.7.10_3.2.1.jar) and buildcraft-7.0.20.jar I've got an error in logfile:

<pre>[08:41:44] [Server thread/ERROR] [PowerConverters/PowerConverters]: Buildcraft recipe is missing items, not adding Power Converters converter recipes.
[08:41:44] [Server thread/WARN] [/PowerConverters]: java.lang.RuntimeException: Invalid shaped ore recipe: TGT, #S#, T#T, T, buildcraft.transport.ItemPipe@188ae7f0, S, buildcraft.transport.BlockFilteredBuffer@72cb7bf9, #, null, G, gearGold, 1xtile.powerconverters.common@2
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at net.minecraftforge.oredict.ShapedOreRecipe.<init>(ShapedOreRecipe.java:122)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at powercrystals.powerconverters.crafting.mods.RecipeBuildCraft.registerRecipes(RecipeBuildCraft.java:55)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at powercrystals.powerconverters.PowerConverterCore.postInit(PowerConverterCore.java:137)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:530)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:323)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:286)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
[08:41:44] [Server thread/WARN] [/PowerConverters]: 	at java.lang.Thread.run(Unknown Source)</pre>

Also some BC-based recipes are missing in NEI
This doesn't happen with BC 6.4.9 and the difference is that BuildCraft|Energy:engineBlock  became BuildCraft|Core:engineBlock in BC 7
Couln't check myself if this helps though, as the build failed with dev.calclavia.resonantengine:resonant-engine:3.3.0.368 dependecy broken.

Also, as it seems, the mod still tries to register BC recipes despite the "not adding Power Converters converter recipes." phrase.

**Comment by akrieger** [comment]
Can confirm, BC input/outputs missing with BC7 and latest jenkins build of Power Converters. Not the worst if you're using Forestry (which is what I needed this mod for, cause Forestry uses RF), because it has an EU->MJ engine, but still stinks.

**Comment by akrieger** [comment]
I get the same error logs.
